### ISSUE TITLE
Maximum number of sensors

### ISSUE THREAD

**Issue by cpatel245** [stytim/k4a-calibration#4]
Hi @stytim,

I was just wondering, How many numbers of Azure Kinect sensors could be calibrated with this method?
Is it also possible to calibrate 4 sensors (each placed at 90 degrees for full 360 reconstruction?)

**Comment by stytim** [comment]
Hi, in the picture I showed in the README file, it is 4 Azure Kinect sensors. In theory, there is no limitation of number of sensors as long as they can all see the marker, and have overlapping region.

**Comment by cpatel245** [comment]
Hi, 
And regarding ChAruco markers, 
Have you used the same ChAruco board on all faces of the cube?

And if you could also elaborate more on specifics of ChAruco Board (marker row, columns, size etc) that would be also great.

**Comment by stytim** [comment]
I have not used the ChArUco board on all faces, but here is a good example: [https://ieeexplore.ieee.org/document/9376321](https://ieeexplore.ieee.org/document/9376321). I have tried using only 1 ChArUco board for calibration, but if you put the camera too far away from the board, it will be hard to detect it. The configuration of the board is included here: [https://github.com/stytim/k4a-calibration/blob/master/include/camera_extrinsics.hpp#L145-L146](https://github.com/stytim/k4a-calibration/blob/master/include/camera_extrinsics.hpp#L145-L146)

**Comment by cpatel245** [comment]
Hi @stytim ,

Managed to stitch the point clouds using ArucoCube. I am not using IMU readings to align the point clouds.
But still I have some artefacts/edges which degrades the quality of the point clouds. 
Did you also face same problem?

![image](https://user-images.githubusercontent.com/51653105/141318275-a1953c6f-16de-4820-b590-75187316c60d.png) 
![image](https://user-images.githubusercontent.com/51653105/141318445-dc40f4c9-6b52-4a71-a77a-b582accf220d.png) ![image](https://user-images.githubusercontent.com/51653105/141318814-3dce0dc1-2a8f-499e-a1c6-8248ad060b21.png)
